---
# from https://github.com/geerlingguy/ansible-role-ansible/blob/master/tasks/setup-Ubuntu.yml

- name: Install apt-add-repository
  apt:
    name: software-properties-common #python-software-properties
    state: present

- name: Add ansible repository
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install latest version of Ansible
  apt:
    name: ansible
    state: latest
