---
- name: Install python dev and other dev
  apt: name={{ item }}
  with_items:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip
  tags: ansible

- name: Install ansible
  pip: name=ansible
  tags: ansible
